name: Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Use Golang
              uses: actions/setup-go@v3
              with:
                  go-version-file: go.mod
            - name: Install dependencies
              run: npm ci
            - name: Run TypeScript type checking
              run: npm run check-types
            - name: Build the app
              run: npm run build
            - name: Run tests (if there are any)
              run: npm test --if-present
